name: Extract external resources

on:
  push:
  schedule:
    - cron: '0 21 */14 * *'

jobs:
  extract:
    name: Extract data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build Docker image
        run: |
          docker build -t quickdocs/external-resources .
      - name: Extract
        run: |
          docker run --rm -i -v ${PWD}/output:/app/output quickdocs/external-resources
      - name: Upload to GCS
        if: github.ref == 'refs/heads/master'
        run: |
          cd output/
          for file in `find cliki -not -type d`; do
            gsutil -h "Content-Type:application/json" cp $file gs://quickdocs-resources/$file
          done
